import type { Metadata } from "next";
import "../styles/reset.scss";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => {
  return (
    <html lang="ru">
      <body>
        {children}
      </body>
    </html>
  );
}


export default RootLayout;